### PR TITLE
Remove need to manually update index.js version

### PR DESCRIPTION
**Pull request by sirsavary**

### CODE REVIEW

**Comment by addaleax** [comment]
You’d probably need something a bit different – `require("./package.json")` might work. Btw, only release commits would contain changes to the versions, so I’m not sure this is worth the trouble.

**Comment by sirsavary** [comment]
Whoops, that's what I get for writing this without coffee.

I wrote this PR after seeing the one before mine, it just seems like something that's relatively easy to miss and is easily fixed. Having to update the version in two places isn't immediately obvious to new contributors and just adds more stuff to keep track of.

**Comment by addaleax** [comment]
> Having to update the version in two places isn't immediately obvious to new contributors and just adds more stuff to keep track of.

Yeah, but that's not an issue if it's clear to contributors that they don't need to touch that version number :)

I'll try to make a PR that adds a comment above the relevant lines and makes that a bit more clear.

**Comment by addaleax** [comment]
I’m closing this for the reasons given above – sorry.

**Pull request closed without merging**
