### PR TITLE
Support context-aware

### PR DESCRIPTION
**Pull request by jc-lab**

### CODE REVIEW

**Comment by jc-lab** [comment]
Hi, @addaleax Thanks for the comment.

I added a commit to solve the static constructors.

Please review.

I hope to be able to use lzma-native on the thread.

Thanks!

**Comment by addaleax** [comment]
@jc-lab Thanks! I think it might be easiest to remove the constructor references, though, and just disable calls without `new` in those cases.

If you do pursue the current route, you’ll also need to use a cleanup hook (`AddCleanupHook`, sadly `Nan` doesn’t provide a wrapper for that) that deletes the `AddonContext` so that there is no memory leak when loading the addon more than once.

I’ve also rebased https://github.com/addaleax/lzma-native/pull/72 – switching to N-API altogether would be the ideal solution here, imo. When I originally tried, I had some issues with getting CI to pass, but I feel like there might be a chance some fixes in upstream Node.js have resolved those.

**Comment by jc-lab** [comment]
@addaleax 

I also think N-API conversion is a good idea.

I looking forward to the N-API version soon!

**Comment by addaleax** [comment]
Okay, published v6.0.0 with N-API and thus with context-awareness – let me know how that works for you! :)

I’ll be closing this as there shouldn’t be anything more to do in order to support worker threads.

(Happy new year btw!)

**Comment by jc-lab** [comment]
@addaleax 

Working good! Thank you.

Happy new year :)

**Pull request closed without merging**
